String descriptionA = "Aedes aegypti, the yellow fever mosquito, is a mosquito that can spread dengue fever, chikungunya, Zika fever, Mayaro and yellow fever viruses, and other disease agents. The mosquito can be recognized by black and white markings on its legs and a marking in the form of a lyre on the upper surface of its thorax. This mosquito originated in Africa, but is now found in tropical, subtropical and temperate regions throughout the world.Biology Aedes aegypti is a 4–7 millimetres (5⁄32–35⁄128 in) long, dark mosquito which can be recognized by white markings on its legs and a marking in the form of a lyre on the upper surface of its thorax. Females are larger than males. Microscopically females possess small palps tipped with silver or white scales, and their antennae have sparse short hairs, whereas those of males are feathery. Aedes aegypti can be confused with Aedes albopictus without a magnifying glass: the latter have a white stripe on the top of the mid thorax.";
String descriptionB = "Aedes albopictus (Stegomyia albopicta), from the mosquito (Culicidae) family, also known as the (Asian) tiger mosquito or forest mosquito, is a mosquito native to the tropical and subtropical areas of Southeast Asia. In the past few centuries, however, this species has spread to many countries through the transport of goods and international travel. It is characterized by the white bands on its legs and body.This mosquito has become a significant pest in many communities because it closely associates with humans (rather than living in wetlands), and typically flies and feeds in the daytime in addition to at dusk and dawn. The insect is called a tiger mosquito for its striped appearance, which resembles that of the tiger. Ae. albopictus is an epidemiologically important vector for the transmission of many viral pathogens, including the yellow fever virus, dengue fever, and Chikungunya fever, as well as several filarial nematodes such as Dirofilaria immitis. Aedes albopictus is capable of hosting the Zika virus and is considered a potential vector for Zika transmission among humans.";
String descriptionC = "Anopheles arabiensis is a zoophilic species of mosquito and a vector of disease endemic to Africa.Polytene chromosomes have a high degree of gene polymorphism due to paracentric inversions. This is also unusually high for the genus. (See the chapter by Kitzmiller 1976.) There is a well studied adaptive inversion. Kirkpatrick and Barrett 2015 and Sharakhov et al. 2006 find an inversion providing A. arabiensis with some of its adaptation to arid environments. They also find this inversion has been introgressed across more widely in the genus, providing similar adaptive benefit.";
String descriptionD = "The Anopheles gambiae complex consists of at least seven morphologically indistinguishable species of mosquitoes in the genus Anopheles. The complex was recognised in the 1960s and includes the most important vectors of malaria in sub-Saharan Africa, particularly of the most dangerous malaria parasite, Plasmodium falciparum.[2] It is one of the most efficient malaria vectors known. The An. gambiae mosquito additionally transmits Wuchereria bancrofti which causes lymphatic filariasis, a symptom of which is elephantiasis. Discovery and elements The Anopheles gambiae complex or Anopheles gambiae sensu lato was recognized as a species complex only in the 1960s. The A. gambiae complex consists of";
String descriptionE = "Culex pipiens, commonly referred to as the common house mosquito, is a species of mosquito. House mosquitoes are some of the most common mosquitoes. More specifically, Culex pipiens is considered as the northern house mosquito, as it is the most common mosquito to the northern regions of the US. North of the 39th parallel north in the US, only C. pipiens are present, whereas south of the 36th parallel north, only C. quinquefasciatus (commonly known as the southern house mosquito) are present.[1] Additionally, they can be found in both urban and suburban temperate and tropical regions across the world.[2] Culex pipiens' diet typically consists of vertebrate blood, as they consume human blood, but prefer bird blood of species that are nearly linked to human interaction, such as doves and pigeons.[3] Furthermore, at the end of the summer and the start of the fall season before it is time for them to overwinter, C. pipiens subsist on nectar and other sugary food sources in order to store fat.";
String descriptionF = "Culex quinquefasciatus (originally named Culex fatigans), commonly known as the southern house mosquito, is a medium-sized mosquito found in tropical and subtropical regions of the world. It is a vector of Wuchereria bancrofti, avian malaria, and arboviruses including St. Louis encephalitis virus, Western equine encephalitis virus, Zika virus[1] and West Nile virus.[2][3] It is taxonomically regarded as a member of the Culex pipiens species complex.[4][5] Its genome was sequenced in 2010, and was shown to have 18,883 protein-coding genes.[6]";

String nameA = "Ae. aegypti";
String nameB = "Ae. albopictus";
String nameC = "An. arabiensis";
String nameD = "An. gambiae";
String nameE = "C. pipiens";
String nameF = "C. quinquefasciatus";


String pictureA = "assets/images/A.jpg";
String pictureB = "assets/images/B.jpg";
String pictureC = "assets/images/C.jpg";
String pictureD = "assets/images/D.jpg";
String pictureE = "assets/images/E.jpg";
String pictureF = "assets/images/F.jpg";
